# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
 
pool:
  vmImage: windows-latest
  #env:
    #PAYLOAD: ${{toJSON(github.event.client_payload)}}
parameters:
  - name: postRequestBody
    type: object
    default: |
      {}
steps:
  - script: |
      echo "Recieved JSON payload: $(postRequestBody)"
      attibutes=$(echo $(postRequestBody) | jq -r
      '.attributes | to_entries[] | "\(.key)=\(.value)"')
      curl --help
      echo "Hello World"
      node --version
      node hello.js
      
    displayName: 'Download index.js from GitHub'
    
      
   
      
    
  

  
    
      

  